/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Judge, Project, EvaluationCriterion } from './types';

export const INITIAL_JUDGES: Judge[] = [
  {
    id: '1',
    name: 'Dr. Elena Rodriguez',
    role: 'MIT Media Lab',
    organization: 'MIT Media Lab',
    avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDNNot0yKU3DmmZA9DxLfJ8NdGSSYPEYyZXbPsbC9QLwMqwNepWfb6u27DMH_BKD1mONG_ZjqpsxS35nuUxH8vSldCYhQg_CnuMtxIesbIXj-21901YhBsP3w7igHhMuG_pPIvn-Glf4LNtRwjtf0RcgNTzQLevJ5gFIjfrPHdq522h6T43T7GKxo0eTJQc32TNMbxTXd5nyObMtbDXVCijejiJ6-zBLV7wn8ORgUDWOVDo4YbMeLuRawFFSFhTu9KYre7775gRTWs',
    expertise: 'AI/ML',
    assignedProjectsCount: 12,
    completedEvaluations: 12,
    avgScoreGiven: 8.4,
    isOverCapacity: false,
  },
  {
    id: '2',
    name: 'Marcus Chen',
    role: 'Stripe Eng Lead',
    organization: 'Stripe Eng Lead',
    avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBxuM0eJjEITzhtmMmDTjpLw635AuQMc5cBa32317hKnvOw1V1dUamBCKSHl8WvplOfhc0zyz2XsGfWPaTkawFLTPr0C5WaeRTcKtD4P1pX1F2bZa61d0qRSjaEtw6XDqzGnQvx-szid4-VxM967XUd1tMABdi-uVoT_tkhphSQthbaEvGSX_YJK1HpCZJ3EgXCFSjqSxw3D37OPKUujQUeovps0OGARicn7GnVQtl6PJCJgCnYKw87Ey5qwz1GinKQlRfE4G0EpqE',
    expertise: 'FinTech',
    assignedProjectsCount: 18,
    completedEvaluations: 8,
    avgScoreGiven: 7.2,
    isOverCapacity: true,
  },
  {
    id: '3',
    name: 'Jordan Davis',
    role: 'Independent Consultant',
    organization: 'Independent Consultant',
    expertise: 'UI/UX Design',
    assignedProjectsCount: 10,
    completedEvaluations: 8,
    avgScoreGiven: 9.1,
    isOverCapacity: false,
  },
  {
    id: '4',
    name: 'Sarah Jenkins',
    role: 'HealthCore CTO',
    organization: 'HealthCore CTO',
    avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAy0Xg4PiSNHrJYjvMrXcgoq2LnOysaN4qE4R6JWKgPJR8vCfKp2oKh6WquwMspUwmVb5mF19OLNDcNvZJ0sokjloqgnHdQgz6TUU1NQ9_mTeFv69sDZ_-jrMzsI0u-Bw5IvOfQ8jTjmuWz8ln8It2WZ3CZRqq3WJg85yq5wGJrFX4rRQ6hwobmjLXY4HZppBKyDDlRB-x1QYE4b_JVp888v_Xi-SOT24YeVj6p81FEs9OLzxO35YMNjiRgUzio7KeuKPxnssTiuQo',
    expertise: 'HealthTech',
    assignedProjectsCount: 15,
    completedEvaluations: 3,
    avgScoreGiven: 6.8,
    isOverCapacity: true,
  },
  {
    id: '5',
    name: 'Dr. Alex Rivera',
    role: 'AI Researcher',
    organization: 'Stanford AI Lab',
    expertise: 'AI/ML',
    assignedProjectsCount: 14,
    completedEvaluations: 13,
    avgScoreGiven: 8.7,
    isOverCapacity: false,
  },
  {
    id: '6',
    name: 'Sophia Martinez',
    role: 'Senior Product Designer',
    organization: 'Figma',
    expertise: 'UI/UX Design',
    assignedProjectsCount: 8,
    completedEvaluations: 8,
    avgScoreGiven: 9.3,
    isOverCapacity: false,
  },
  {
    id: '7',
    name: 'David Kim',
    role: 'Lead Architect',
    organization: 'Wise',
    expertise: 'FinTech',
    assignedProjectsCount: 16,
    completedEvaluations: 6,
    avgScoreGiven: 7.5,
    isOverCapacity: true,
  },
  {
    id: '8',
    name: 'Emily Watson',
    role: 'Research Lead',
    organization: 'BioTech Corp',
    expertise: 'HealthTech',
    assignedProjectsCount: 9,
    completedEvaluations: 9,
    avgScoreGiven: 8.0,
    isOverCapacity: false,
  },
  {
    id: '9',
    name: 'Michael Chang',
    role: 'Staff Engineer',
    organization: 'Google Research',
    expertise: 'AI/ML',
    assignedProjectsCount: 15,
    completedEvaluations: 14,
    avgScoreGiven: 8.9,
    isOverCapacity: false,
  },
  {
    id: '10',
    name: 'Lisa Patel',
    role: 'Product Manager',
    organization: 'Plaid',
    expertise: 'FinTech',
    assignedProjectsCount: 11,
    completedEvaluations: 9,
    avgScoreGiven: 8.2,
    isOverCapacity: false,
  },
  {
    id: '11',
    name: 'James O\'Connor',
    role: 'Principal Designer',
    organization: 'Vercel',
    expertise: 'UI/UX Design',
    assignedProjectsCount: 7,
    completedEvaluations: 6,
    avgScoreGiven: 8.8,
    isOverCapacity: false,
  },
  {
    id: '12',
    name: 'Dr. Amara Okafor',
    role: 'Digital Health Director',
    organization: 'NHS Digital',
    expertise: 'HealthTech',
    assignedProjectsCount: 12,
    completedEvaluations: 4,
    avgScoreGiven: 7.0,
    isOverCapacity: false,
  }
];

export const INITIAL_PROJECTS: Project[] = [
  { id: 'p1', title: 'Project Quantum Nexus', track: 'AI/ML', teamName: 'Quantum Coders', assignedJudgeId: '1', evaluationStatus: 'Completed', score: 8.8 },
  { id: 'p2', title: 'EcoStream Analytics', track: 'FinTech', teamName: 'Green Finance', assignedJudgeId: '2', evaluationStatus: 'In Progress' },
  { id: 'p3', title: 'SecureVault Mobile', track: 'FinTech', teamName: 'CyberGuardians', assignedJudgeId: '2', evaluationStatus: 'In Progress' },
  { id: 'p4', title: 'HealthPulse AI', track: 'HealthTech', teamName: 'CardioSmart', assignedJudgeId: '4', evaluationStatus: 'In Progress' },
  { id: 'p5', title: 'Decentralized Credit Hub', track: 'FinTech', teamName: 'BlockChainers', assignedJudgeId: '2', evaluationStatus: 'Pending' },
  { id: 'p6', title: 'Metaverse Canvas', track: 'UI/UX Design', teamName: 'Creative Pixel', assignedJudgeId: '3', evaluationStatus: 'Completed', score: 9.1 },
  { id: 'p7', title: 'CareLoop Patient Portal', track: 'HealthTech', teamName: 'MedTech Innovation', assignedJudgeId: '4', evaluationStatus: 'In Progress' },
  { id: 'p8', title: 'AeroOptima Logistics', track: 'AI/ML', teamName: 'LogiTech', assignedJudgeId: '1', evaluationStatus: 'Completed', score: 8.0 },
  { id: 'p9', title: 'EduGrowth Analytics', track: 'UI/UX Design', teamName: 'EduDesigners', assignedJudgeId: '3', evaluationStatus: 'In Progress' },
  { id: 'p10', title: 'FinFlow Dashboard', track: 'FinTech', teamName: 'Capital Gains', assignedJudgeId: '2', evaluationStatus: 'Completed', score: 7.2 },
  { id: 'p11', title: 'NeuroSight Diagnostic', track: 'HealthTech', teamName: 'BrainVision', assignedJudgeId: '4', evaluationStatus: 'In Progress' },
  { id: 'p12', title: 'SustainaBuild ML', track: 'AI/ML', teamName: 'EcoArchitects', assignedJudgeId: '1', evaluationStatus: 'Completed', score: 8.4 },
  { id: 'p13', title: 'MedPredict AI', track: 'HealthTech', teamName: 'Diagnostic Hub', assignedJudgeId: '4', evaluationStatus: 'Pending' },
  { id: 'p14', title: 'DeFi Lending Pool', track: 'FinTech', teamName: 'YieldFarmers', assignedJudgeId: '2', evaluationStatus: 'In Progress' },
  { id: 'p15', title: 'IntelliTraffic Optimizer', track: 'AI/ML', teamName: 'SmartCity IoT', assignedJudgeId: '5', evaluationStatus: 'Completed', score: 9.0 }
];

export const INITIAL_CRITERIA: EvaluationCriterion[] = [
  { id: 'c1', name: 'Innovation & Originality', weight: 0.25, description: 'Is the solution unique, creative, or novel compared to existing solutions?' },
  { id: 'c2', name: 'Technical Execution & Feasibility', weight: 0.25, description: 'How well-built is the system? Is the architecture robust and the code clean?' },
  { id: 'c3', name: 'User Experience & Design', weight: 0.25, description: 'Is the interface beautiful, accessible, intuitive, and satisfying to use?' },
  { id: 'c4', name: 'Impact & Business Value', weight: 0.25, description: 'Does it solve a real-world problem effectively? Is there a viable model for scale?' }
];
